language: ruby
sudo: false

rvm:
  - 2.5

before_install:
  - gem update --system
  - gem --version

install: bundle install 

script: 
    - bundle update github-pages
    - bundle exec jekyll build

cache: bundler